/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SmartCityRouteImport } from './routes/smart-city'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as PolicySimulatorRouteImport } from './routes/policy-simulator'
import { Route as LoraMeshRouteImport } from './routes/lora-mesh'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as LiveAqiRouteImport } from './routes/live-aqi'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HeatmapsRouteImport } from './routes/heatmaps'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as ExplainableRouteImport } from './routes/explainable'
import { Route as EnforcementRouteImport } from './routes/enforcement'
import { Route as EdgeNodesRouteImport } from './routes/edge-nodes'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DeviceHealthRouteImport } from './routes/device-health'
import { Route as DataTrustRouteImport } from './routes/data-trust'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CloudEdgeRouteImport } from './routes/cloud-edge'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'

const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartCityRoute = SmartCityRouteImport.update({
  id: '/smart-city',
  path: '/smart-city',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicySimulatorRoute = PolicySimulatorRouteImport.update({
  id: '/policy-simulator',
  path: '/policy-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoraMeshRoute = LoraMeshRouteImport.update({
  id: '/lora-mesh',
  path: '/lora-mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveAqiRoute = LiveAqiRouteImport.update({
  id: '/live-aqi',
  path: '/live-aqi',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapsRoute = HeatmapsRouteImport.update({
  id: '/heatmaps',
  path: '/heatmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainableRoute = ExplainableRouteImport.update({
  id: '/explainable',
  path: '/explainable',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementRoute = EnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeNodesRoute = EdgeNodesRouteImport.update({
  id: '/edge-nodes',
  path: '/edge-nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceHealthRoute = DeviceHealthRouteImport.update({
  id: '/device-health',
  path: '/device-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTrustRoute = DataTrustRouteImport.update({
  id: '/data-trust',
  path: '/data-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudEdgeRoute = CloudEdgeRouteImport.update({
  id: '/cloud-edge',
  path: '/cloud-edge',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api': typeof ApiRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/cloud-edge': typeof CloudEdgeRoute
  '/command-center': typeof CommandCenterRoute
  '/complaints': typeof ComplaintsRoute
  '/compliance': typeof ComplianceRoute
  '/data-trust': typeof DataTrustRoute
  '/device-health': typeof DeviceHealthRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/drones': typeof DronesRoute
  '/edge-nodes': typeof EdgeNodesRoute
  '/enforcement': typeof EnforcementRoute
  '/explainable': typeof ExplainableRoute
  '/forecasting': typeof ForecastingRoute
  '/heatmaps': typeof HeatmapsRoute
  '/incidents': typeof IncidentsRoute
  '/intelligence': typeof IntelligenceRoute
  '/live-aqi': typeof LiveAqiRoute
  '/live-map': typeof LiveMapRoute
  '/lora-mesh': typeof LoraMeshRoute
  '/policy-simulator': typeof PolicySimulatorRoute
  '/prediction': typeof PredictionRoute
  '/reports': typeof ReportsRoute
  '/sandbox': typeof SandboxRoute
  '/security': typeof SecurityRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/smart-city': typeof SmartCityRoute
  '/system': typeof SystemRoute
  '/telemetry': typeof TelemetryRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api': typeof ApiRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/cloud-edge': typeof CloudEdgeRoute
  '/command-center': typeof CommandCenterRoute
  '/complaints': typeof ComplaintsRoute
  '/compliance': typeof ComplianceRoute
  '/data-trust': typeof DataTrustRoute
  '/device-health': typeof DeviceHealthRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/drones': typeof DronesRoute
  '/edge-nodes': typeof EdgeNodesRoute
  '/enforcement': typeof EnforcementRoute
  '/explainable': typeof ExplainableRoute
  '/forecasting': typeof ForecastingRoute
  '/heatmaps': typeof HeatmapsRoute
  '/incidents': typeof IncidentsRoute
  '/intelligence': typeof IntelligenceRoute
  '/live-aqi': typeof LiveAqiRoute
  '/live-map': typeof LiveMapRoute
  '/lora-mesh': typeof LoraMeshRoute
  '/policy-simulator': typeof PolicySimulatorRoute
  '/prediction': typeof PredictionRoute
  '/reports': typeof ReportsRoute
  '/sandbox': typeof SandboxRoute
  '/security': typeof SecurityRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/smart-city': typeof SmartCityRoute
  '/system': typeof SystemRoute
  '/telemetry': typeof TelemetryRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api': typeof ApiRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/cloud-edge': typeof CloudEdgeRoute
  '/command-center': typeof CommandCenterRoute
  '/complaints': typeof ComplaintsRoute
  '/compliance': typeof ComplianceRoute
  '/data-trust': typeof DataTrustRoute
  '/device-health': typeof DeviceHealthRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/drones': typeof DronesRoute
  '/edge-nodes': typeof EdgeNodesRoute
  '/enforcement': typeof EnforcementRoute
  '/explainable': typeof ExplainableRoute
  '/forecasting': typeof ForecastingRoute
  '/heatmaps': typeof HeatmapsRoute
  '/incidents': typeof IncidentsRoute
  '/intelligence': typeof IntelligenceRoute
  '/live-aqi': typeof LiveAqiRoute
  '/live-map': typeof LiveMapRoute
  '/lora-mesh': typeof LoraMeshRoute
  '/policy-simulator': typeof PolicySimulatorRoute
  '/prediction': typeof PredictionRoute
  '/reports': typeof ReportsRoute
  '/sandbox': typeof SandboxRoute
  '/security': typeof SecurityRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/smart-city': typeof SmartCityRoute
  '/system': typeof SystemRoute
  '/telemetry': typeof TelemetryRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/api'
    | '/audit'
    | '/citizen'
    | '/cloud-edge'
    | '/command-center'
    | '/complaints'
    | '/compliance'
    | '/data-trust'
    | '/device-health'
    | '/digital-twin'
    | '/drones'
    | '/edge-nodes'
    | '/enforcement'
    | '/explainable'
    | '/forecasting'
    | '/heatmaps'
    | '/incidents'
    | '/intelligence'
    | '/live-aqi'
    | '/live-map'
    | '/lora-mesh'
    | '/policy-simulator'
    | '/prediction'
    | '/reports'
    | '/sandbox'
    | '/security'
    | '/sensors'
    | '/settings'
    | '/smart-city'
    | '/system'
    | '/telemetry'
    | '/users'
    | '/vehicles'
    | '/what-if'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/api'
    | '/audit'
    | '/citizen'
    | '/cloud-edge'
    | '/command-center'
    | '/complaints'
    | '/compliance'
    | '/data-trust'
    | '/device-health'
    | '/digital-twin'
    | '/drones'
    | '/edge-nodes'
    | '/enforcement'
    | '/explainable'
    | '/forecasting'
    | '/heatmaps'
    | '/incidents'
    | '/intelligence'
    | '/live-aqi'
    | '/live-map'
    | '/lora-mesh'
    | '/policy-simulator'
    | '/prediction'
    | '/reports'
    | '/sandbox'
    | '/security'
    | '/sensors'
    | '/settings'
    | '/smart-city'
    | '/system'
    | '/telemetry'
    | '/users'
    | '/vehicles'
    | '/what-if'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/api'
    | '/audit'
    | '/citizen'
    | '/cloud-edge'
    | '/command-center'
    | '/complaints'
    | '/compliance'
    | '/data-trust'
    | '/device-health'
    | '/digital-twin'
    | '/drones'
    | '/edge-nodes'
    | '/enforcement'
    | '/explainable'
    | '/forecasting'
    | '/heatmaps'
    | '/incidents'
    | '/intelligence'
    | '/live-aqi'
    | '/live-map'
    | '/lora-mesh'
    | '/policy-simulator'
    | '/prediction'
    | '/reports'
    | '/sandbox'
    | '/security'
    | '/sensors'
    | '/settings'
    | '/smart-city'
    | '/system'
    | '/telemetry'
    | '/users'
    | '/vehicles'
    | '/what-if'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ApiRoute: typeof ApiRoute
  AuditRoute: typeof AuditRoute
  CitizenRoute: typeof CitizenRoute
  CloudEdgeRoute: typeof CloudEdgeRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ComplianceRoute: typeof ComplianceRoute
  DataTrustRoute: typeof DataTrustRoute
  DeviceHealthRoute: typeof DeviceHealthRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  DronesRoute: typeof DronesRoute
  EdgeNodesRoute: typeof EdgeNodesRoute
  EnforcementRoute: typeof EnforcementRoute
  ExplainableRoute: typeof ExplainableRoute
  ForecastingRoute: typeof ForecastingRoute
  HeatmapsRoute: typeof HeatmapsRoute
  IncidentsRoute: typeof IncidentsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LiveAqiRoute: typeof LiveAqiRoute
  LiveMapRoute: typeof LiveMapRoute
  LoraMeshRoute: typeof LoraMeshRoute
  PolicySimulatorRoute: typeof PolicySimulatorRoute
  PredictionRoute: typeof PredictionRoute
  ReportsRoute: typeof ReportsRoute
  SandboxRoute: typeof SandboxRoute
  SecurityRoute: typeof SecurityRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  SmartCityRoute: typeof SmartCityRoute
  SystemRoute: typeof SystemRoute
  TelemetryRoute: typeof TelemetryRoute
  UsersRoute: typeof UsersRoute
  VehiclesRoute: typeof VehiclesRoute
  WhatIfRoute: typeof WhatIfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-city': {
      id: '/smart-city'
      path: '/smart-city'
      fullPath: '/smart-city'
      preLoaderRoute: typeof SmartCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-simulator': {
      id: '/policy-simulator'
      path: '/policy-simulator'
      fullPath: '/policy-simulator'
      preLoaderRoute: typeof PolicySimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lora-mesh': {
      id: '/lora-mesh'
      path: '/lora-mesh'
      fullPath: '/lora-mesh'
      preLoaderRoute: typeof LoraMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-aqi': {
      id: '/live-aqi'
      path: '/live-aqi'
      fullPath: '/live-aqi'
      preLoaderRoute: typeof LiveAqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmaps': {
      id: '/heatmaps'
      path: '/heatmaps'
      fullPath: '/heatmaps'
      preLoaderRoute: typeof HeatmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainable': {
      id: '/explainable'
      path: '/explainable'
      fullPath: '/explainable'
      preLoaderRoute: typeof ExplainableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement': {
      id: '/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof EnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge-nodes': {
      id: '/edge-nodes'
      path: '/edge-nodes'
      fullPath: '/edge-nodes'
      preLoaderRoute: typeof EdgeNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-health': {
      id: '/device-health'
      path: '/device-health'
      fullPath: '/device-health'
      preLoaderRoute: typeof DeviceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-trust': {
      id: '/data-trust'
      path: '/data-trust'
      fullPath: '/data-trust'
      preLoaderRoute: typeof DataTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-edge': {
      id: '/cloud-edge'
      path: '/cloud-edge'
      fullPath: '/cloud-edge'
      preLoaderRoute: typeof CloudEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ApiRoute: ApiRoute,
  AuditRoute: AuditRoute,
  CitizenRoute: CitizenRoute,
  CloudEdgeRoute: CloudEdgeRoute,
  CommandCenterRoute: CommandCenterRoute,
  ComplaintsRoute: ComplaintsRoute,
  ComplianceRoute: ComplianceRoute,
  DataTrustRoute: DataTrustRoute,
  DeviceHealthRoute: DeviceHealthRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  DronesRoute: DronesRoute,
  EdgeNodesRoute: EdgeNodesRoute,
  EnforcementRoute: EnforcementRoute,
  ExplainableRoute: ExplainableRoute,
  ForecastingRoute: ForecastingRoute,
  HeatmapsRoute: HeatmapsRoute,
  IncidentsRoute: IncidentsRoute,
  IntelligenceRoute: IntelligenceRoute,
  LiveAqiRoute: LiveAqiRoute,
  LiveMapRoute: LiveMapRoute,
  LoraMeshRoute: LoraMeshRoute,
  PolicySimulatorRoute: PolicySimulatorRoute,
  PredictionRoute: PredictionRoute,
  ReportsRoute: ReportsRoute,
  SandboxRoute: SandboxRoute,
  SecurityRoute: SecurityRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  SmartCityRoute: SmartCityRoute,
  SystemRoute: SystemRoute,
  TelemetryRoute: TelemetryRoute,
  UsersRoute: UsersRoute,
  VehiclesRoute: VehiclesRoute,
  WhatIfRoute: WhatIfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
